services:
  db:
    image: postgres:15.5
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rkv
      POSTGRES_PASSWORD: supersecret
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_DB: rkv
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

volumes:
  pgdata:
